require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# 今のところ必要性を感じない
Style/Documentation:
  Enabled: false

# 常にダブルクォートの方がいい
Style/StringLiterals:
  EnforcedStyle: double_quotes
